// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfc0Zps4bqmae_NAytW7HI2w_GCiW8DYY',
    appId: '1:113118213903:web:7fa24e66f39402cb36307a',
    messagingSenderId: '113118213903',
    projectId: 'growy-4036d',
    authDomain: 'growy-4036d.firebaseapp.com',
    storageBucket: 'growy-4036d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2IBRDtOSvnYlFbTf_SuXYzKwecKh68BA',
    appId: '1:113118213903:android:5a2e4251732d8df136307a',
    messagingSenderId: '113118213903',
    projectId: 'growy-4036d',
    storageBucket: 'growy-4036d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0sR9MUzgeautapUjfkNiBKj4bWAZaSG8',
    appId: '1:113118213903:ios:6b92816dafda619336307a',
    messagingSenderId: '113118213903',
    projectId: 'growy-4036d',
    storageBucket: 'growy-4036d.firebasestorage.app',
    iosBundleId: 'com.growy.growy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0sR9MUzgeautapUjfkNiBKj4bWAZaSG8',
    appId: '1:113118213903:ios:6b92816dafda619336307a',
    messagingSenderId: '113118213903',
    projectId: 'growy-4036d',
    storageBucket: 'growy-4036d.firebasestorage.app',
    iosBundleId: 'com.growy.growy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfc0Zps4bqmae_NAytW7HI2w_GCiW8DYY',
    appId: '1:113118213903:web:e1536fba5389c6f836307a',
    messagingSenderId: '113118213903',
    projectId: 'growy-4036d',
    authDomain: 'growy-4036d.firebaseapp.com',
    storageBucket: 'growy-4036d.firebasestorage.app',
  );
}
